# Generated by Django 3.2.12 on 2022-05-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('states', models.TextField()),
                ('currentState', models.TextField()),
                ('isOnline', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Runfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('qOrder', models.PositiveIntegerField(default=0)),
                ('startTime', models.DateTimeField(null=True)),
                ('deviceStates', models.JSONField(null=True)),
                ('runTime', models.FloatField(default=0)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
