# Generated by Django 3.2.12 on 2022-05-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slow_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runfile',
            name='runtime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='runfile',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
