# Generated by Django 3.2.12 on 2022-05-06 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slow_control', '0002_auto_20220506_0135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
