# Configuration of python black settings goes here
# When calling python black on this directory it searches 
# automatically for a file named `pyproject.toml`

[tool.black]
line-length = 200
skip-string-normalization = true
extend_exclude = '''(
    fast_daq_worker/sis3316 |
    fast_daq_worker/tools |
    slow_control_worker/switcher |
    slow_control_worker/zmqLANL
)
'''
