# Generated by Django 3.2.12 on 2022-06-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Histogram',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('data', models.JSONField(null=True)),
                ('xrange', models.JSONField(null=True)),
                ('yrange', models.JSONField(null=True)),
                ('len', models.PositiveBigIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('histIDs', models.JSONField(null=True)),
                ('isLive', models.BooleanField()),
            ],
        ),
    ]
