# Generated by Django 3.2.12 on 2022-06-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('deviceOptions', models.JSONField(null=True)),
                ('isOnline', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RunConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('lastSaved', models.DateTimeField(null=True)),
                ('lastLoaded', models.DateTimeField(null=True)),
                ('priority', models.IntegerField(default=0)),
                ('totalTime', models.FloatField(default=0)),
                ('steps', models.JSONField(null=True)),
                ('status', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
