name: Heroku_Deployment

# This workflow simply deploys the repo to Heroku
# Configuration on the Heroku end is done
# in requirements.txt, runtime.txt, and Profile
# in the root directory

on:
  push:
    branches: [update-load-config-mutation]

jobs:
  builds_successfully:
    runs-on: ubuntu-20.04
    environment:
      name: "Staging"
      url: "https://lane-server.herokuapp.com/graphql/"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "lane-server"
          heroku_email: "douglas.kt.wong@gmail.com"
          healthcheck: "https://lane-server.herokuapp.com/graphql/"
          branch: update-load-config-mutation
        env: # Variables in this section must start with HD_
          HD_DISABLE_COLLECTSTATIC: True # Disable collection of static pages for django
          HD_LANE_SECRET_KEY: ${{secrets.LANE_SECRET_KEY}}
          HD_LANE_DEBUG: False
